### PR TITLE
add interactive map to map details and add as a filter

### PR DESCRIPTION
**Pull request by humanitariandata**
Hi Dan,

Dale asked me to make the changes to add interactive map links to the mapfolio. I have implemented and tested it.

Please note that I have created two additional comments at the end of the data file:
- hasInteractiveMap ("Yes", "No"), which should be set to either for all rows
- interactiveMapLink (url): which should be set for all rows that have "Yes" in the previous collumn

Could you pull it and update the mapfolio?

Regards,

Maarten

### CODE REVIEW

**Comment by dalekunce** [comment]
@maarten can you pull in the latest changes from the gh-pages branches and resubmit.

**Comment by humanitariandata** [comment]
I don't really see why I have to pull latest changes from the upstream gh-pages, since there are no code changes. Only data changes (which I cannot keep up with anyway). That is why the pull request explains how to update the data model.

**Comment by danbjoseph** [comment]
The data is code as far as git is concerned. Why are you git-ignoring the bower_components? That folder contains js and css files that need to be in the repository for the gh-pages page to render.

**Comment by humanitariandata** [comment]
Ah my bad, I created a local instance of nodejs to run the site and thought I had created the bower_components. But its in your repository also.

**Comment by danbjoseph** [comment]
you should check out
`python -m SimpleHTTPServer`

**Pull request merged**
